In [ ]:
import numpy as np 
from matplotlib import pyplot as plt

In [ ]:
from colorama import Style, Fore, Back
blk = Style.BRIGHT + Fore.BLACK
red = Style.BRIGHT + Fore.RED
blu = Style.BRIGHT + Fore.BLUE
grn_bck = Back.GREEN
res = Style.RESET_ALL

import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

# Exercise 5-1.
> This exercise will help you gain familiarity with indexing matrix elements. Create a 3 × 4 matrix using np.arange(12).reshape(3,4). Then write Python code to extract the element in the second row, fourth column. Use softcoding so that you can select different row/column indices. Print out a message like the following: The matrix element at index (2,4) is 7.

In [ ]:
m = np.arange(12).reshape(3,4)

print(f"The matrix element at index (2,4) is {red}{m[1,3]}{res}.")

# Exercise 5-2.
> This and the following exercise focus on slicing matrices to obtain submatrices. Start by creating matrix C in Figure 5-6, and use Python slicing to extract the submatrix comprising the first five rows and five columns. Let’s call this matrix C1. Try to reproduce Figure 5-6, but if you are struggling with the Python visualization coding, then just focus on extracting the submatrix correctly.

In [4]:
C = np.arange(100).reshape((10,10))

sub_a = C[0:5, 0:5]

fig = make_subplots(rows=1, cols=2, subplot_titles=('Original matrix', 'Submatrix'))

fig.add_trace(go.Heatmap(z=C, colorscale='gray', showscale=False), row=1, col=1)
fig.add_shape(type='line', x0=4.5, y0=-0.5, x1=4.5, y1=9.5, line=dict(color='white', dash='dash'), row=1, col=1)
fig.add_shape(type='line', x0=-0.5, y0=4.5, x1=9.5, y1=4.5, line=dict(color='white', dash='dash'), row=1, col=1)

for (j, i), num in np.ndenumerate(C):
    fig.add_annotation(x=i, y=j, text=str(num), showarrow=False, font=dict(color='white'), row=1, col=1)

fig.add_trace(go.Heatmap(z=sub_a, colorscale='gray', showscale=False), row=1, col=2)
for (j, i), num in np.ndenumerate(sub_a):
    fig.add_annotation(x=i, y=j, text=str(num), showarrow=False, font=dict(color='white'), row=1, col=2)

fig.show()     

![Alt text](image-6.png)

# Exercise 5-3.
> Expand this code to extract the other four 5 × 5 blocks. Then create a new matrix with those blocks reorganized according to Figure 5-7.

In [5]:
newM = np.empty(C.shape, dtype='int')

newM[0:5,0:5] = C[5:, 5:]
newM[:5, 5:] = C[5:, :5]
newM[5:, :5] = C[:5, 5:]
newM[5:, 5:] = C[:5, :5]

fig = make_subplots(rows=1, cols=2, subplot_titles=('Original matrix', 'New matrix'))

fig.add_trace(go.Heatmap(z=C, colorscale='gray', showscale=False), row=1, col=1)
for (j, i), num in np.ndenumerate(C):
    fig.add_annotation(x=i, y=j, text=str(num), showarrow=False, font=dict(color='white'), row=1, col=1)

fig.add_trace(go.Heatmap(z=newM, colorscale='gray', showscale=False), row=1, col=2)
for (j, i), num in np.ndenumerate(newM):
    fig.add_annotation(x=i, y=j, text=str(num), showarrow=False, font=dict(color='white'), row=1, col=2)

fig.show()

![Alt text](image-7.png)

# Exercise 5-4.
> Implement matrix addition element-wise using two for loops over rows and columns. What happens when you try to add two matrices with mismatching sizes? This exercise will help you think about breaking down a matrix into rows, columns, and individual elements.

In [6]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(3,4)
c = np.arange(12).reshape(3,4)
for i in range(3):
    for j in range(4):
        c[i,j] = a[i,j] + b[i,j]

print(f"{blk}{a}{res}\n+\n{blk}{b}{res}\n=\n{red}{c}{res}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
+
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
=
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


# Exercise 5-5.
> Matrix addition and scalar multiplication obey the mathematical laws of commutivity and distributivity. That means that the following equations give the same results (assume that the matrices A and B are the same size and that σ is some scalar):
$$σ A + B = σA + σB = Aσ + Bσ$$
> Rather than proving this mathematically, you are going to demonstrate it through coding. In Python, create two random-numbers matrices of size 3 × 4 and a random scalar. Then implement the three expressions in the previous equation. You’ll need to figure out a way to confirm that the three results are equal. Keep in mind that tiny computer precision errors in the range of 10−15 should be ignored.

In [7]:
a = np.random.rand(3,4)
b = np.random.rand(3,4)
s = np.random.rand(1)

c1 = s * (a + b)


c2 = s * a + s * b

print(f"{blk}{s}{res} * ({blk}{a}{res} + {blk}{b}{res}) = {red}{c1}{res}")
print(f"{blk}{s}{res} * {blk}{a}{res} + {blk}{s}{res} * {blk}{b}{res} = {red}{c2}{res}")

err = np.abs(c1 - c2)
print(70*'=')
print(f"Maximum Precision Error: {red}{err.max()}{res}")

[0.45350818] * ([[0.93170889 0.27080606 0.7079623  0.63150472]
 [0.11950392 0.26922182 0.44718477 0.01510972]
 [0.14675351 0.8582505  0.61545711 0.75964493]] + [[0.41284527 0.81636362 0.13436261 0.72756753]
 [0.89108023 0.89965719 0.04819997 0.5062318 ]
 [0.30179189 0.33718342 0.73401431 0.64135648]]) = [[0.60976631 0.49304034 0.38200124 0.61635038]
 [0.45830818 0.5300962  0.22466103 0.23643265]
 [0.20341901 0.54213907 0.61199633 0.6353656 ]]
[0.45350818] * [[0.93170889 0.27080606 0.7079623  0.63150472]
 [0.11950392 0.26922182 0.44718477 0.01510972]
 [0.14675351 0.8582505  0.61545711 0.75964493]] + [0.45350818] * [[0.41284527 0.81636362 0.13436261 0.72756753]
 [0.89108023 0.89965719 0.04819997 0.5062318 ]
 [0.30179189 0.33718342 0.73401431 0.64135648]] = [[0.60976631 0.49304034 0.38200124 0.61635038]
 [0.45830818 0.5300962  0.22466103 0.23643265]
 [0.20341901 0.54213907 0.61199633 0.6353656 ]]
Maximum Precision Error: 1.1102230246251565e-16


# Exercise 5-6.
> Code matrix multiplication using for loops. Confirm your results against using the numpy @ operator. This exercise will help you solidify your understanding of matrix multiplication, but in practice, it’s always better to use @ instead of writing out a double for loop.

In [8]:
a = np.random.randint(0, 10, (3,4))
b = np.random.randint(0, 10, (4,3))

c = np.zeros((3, 3))

for i in range(3): 
    for j in range(3):
            c[i,j] += np.dot(a[i,:].T, b[:,j])

print(f"{blk}{a}{res}\n*\n{blk}{b}{res}\n=\n{red}{c}{res}")

err = np.abs(a@b - c)
print(70*'=')
print(f"Maximum Precision Error: {red}{err.max()}{res}")

[[8 1 2 0]
 [7 4 9 2]
 [5 8 5 6]]
*
[[7 2 1]
 [0 4 8]
 [2 9 0]
 [6 7 4]]
=
[[ 60.  38.  16.]
 [ 79. 125.  47.]
 [ 81. 129.  93.]]
Maximum Precision Error: 0.0


# Exercise 5-7.
> Confirm the LIVE EVIL rule using the following five steps: (1) Create four matrices
of random numbers, setting the sizes to be L ∈ ℝ2 × 6, I ∈ ℝ6 × 3, V ∈ ℝ3 × 5, and
E ∈ ℝ5 × 2. (2) Multiply the four matrices and transpose the product. (3) Transpose
each matrix individually and multiply them without reversing their order. (4) Trans‐
pose each matrix individually and multiply them reversing their order according to
the LIVE EVIL rule. Check whether the result of step 2 matches the results of step 3
and step 4. (5) Repeat the previous steps but using all square matrices.

In [9]:
# 2*6, 6*3, 3*5, 5*2

a = np.random.randint(0, 10, (2,6))
b = np.random.randint(0, 10, (6,3))
c = np.random.randint(0, 10, (3,5))
d = np.random.randint(0, 10, (5,2))

e = a @ b @ c @ d

at, bt, ct, dt = a.T, b.T, c.T, d.T

# etf = at @ bt @ ct @ dt -> Error ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

et = dt @ ct @ bt @ at

err = np.abs(e - et.T)
print(f"Maximization Precision Error: {red}{err.max()}{res}")


Maximization Precision Error: 0


In [10]:
# Using Square Matrices
a = np.random.randint(0, 10, (3,3))
b = np.random.randint(0, 10, (3,3))
c = np.random.randint(0, 10, (3,3))
d = np.random.randint(0, 10, (3,3))

e = a @ b @ c @ d

at, bt, ct, dt = a.T, b.T, c.T, d.T

etf = at @ bt @ ct @ dt

et = dt @ ct @ bt @ at

print(f"Different order of multiplication: {red}{np.allclose(e, et.T)}{res}")
print(f"Transpose of the multiplication: {red}{np.allclose(e, etf.T)}{res}")

Different order of multiplication: True
Transpose of the multiplication: False


# Exercise 5-8.
> In this exercise, you will write a Python function that checks whether a matrix is
symmetric. It should take a matrix as input, and should output a boolean True if
the matrix is symmetric or False if the matrix is nonsymmetric. Keep in mind that
small computer rounding/precision errors can make “equal” matrices appear unequal.
Therefore, you will need to test for equality with some reasonable tolerance. Test the
function on symmetric and nonsymmetric matrices.

In [11]:
def is_sym(m): 
    return np.allclose(m, m.T)

symm = np.eye(3)
asymm = np.random.randint(0, 10, (3,3))

print(f"Symmetric matrix: {red}{is_sym(symm)}{res}")
print(f"Asymmetric matrix: {red}{is_sym(asymm)}{res}")

Symmetric matrix: True
Asymmetric matrix: False


# Exercise 5-9.
>I mentioned that there is an additive method for creating a symmetric matrix from a
nonsymmetric square matrix. The method is quite simple: average the matrix with its
transpose. Implement this algorithm in Python and confirm that the result really is
symmetric. (Hint: you can use the function you wrote in the previous exercise!)

In [12]:
asymmT = asymm.T

symm_asymm = (asymm + asymmT) / 2

print(f"Symmetric matrix: {red}{is_sym(symm_asymm)}{res}")

Symmetric matrix: True


# Exercise 5-10.
>Repeat the second part of Exercise 3-3 (the two vectors in ℝ3), but use matrix-vector
multiplication instead of vector-scalar multiplication. That is, compute As instead of
σ1v1 + σ2v2.

In [13]:
import plotly.graph_objects as go

# As a matrix with two columns in R3, instead of two separate vectors
A = np.array([[3, 0], [5, 2], [1, 2]])

xlim = [-4,4]
scalars = np.random.uniform(low=xlim[0],high=xlim[1],size=(100,2))

# create random points
points = np.zeros((100,3))
for i in range(len(scalars)):
  points[i,:] = A@scalars[i]

# draw the dots in the figure
fig = go.Figure( data=[go.Scatter3d(x=points[:,0], y=points[:,1], z=points[:,2], mode='markers')])
fig.show()

![Alt text](image-5.png)

# Exercise 5-11.
> Diagonal matrices have many interesting properties that make them useful to work
with.

In [15]:
n = 4

# create "base" matrices
O = np.ones((n,n))
S = np.diag(np.arange(1,n+1)**2)

pre = S@O
post = O@S

both = S@O@S

print(f"{blk}S{res} =\n{red}{S}{res}")
print(f"{blk}O{res} =\n{red}{O}{res}")
print(f"{blk}pre{res} =\n{red}{pre}{res}")
print(f"{blk}post{res} =\n{red}{post}{res}")
print(f"{blk}both{res} =\n{red}{both}{res}")


S =
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
O =
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
pre =
[[ 1.  1.  1.  1.]
 [ 4.  4.  4.  4.]
 [ 9.  9.  9.  9.]
 [16. 16. 16. 16.]]
post =
[[ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]
 [ 1.  4.  9. 16.]]
both =
[[  1.   4.   9.  16.]
 [  4.  16.  36.  64.]
 [  9.  36.  81. 144.]
 [ 16.  64. 144. 256.]]


# Exercise 5-12.
> Another fun fact: matrix multiplication is the same thing as Hadamard multiplication
for two diagonal matrices. Figure out why this is using paper and pencil with two
3 × 3 diagonal matrices, and then illustrate it in Python code.

In [16]:
# Create two diagonal matrices
N = 5
D1 = np.diag( np.random.randn(N) )
D2 = np.diag( np.random.randn(N) )

# two forms of multiplication
hadamard = D1*D2
standard = D1@D2

print(f"Is Hadamard product commutative? {red}{np.allclose(hadamard, D2*D1)}{res}")

Is Hadamard product commutative? True
